import {
  BfsiIcon,
  CartIcon,
  EdtechIcon,
  FastMoveGoodsIcon,
  GoventitiesIcon,
  HealthcareIcon,
  ManufacturingIcon,
  MarketingIcon,
  OttIcon,
  RealestateIcon,
  RestaurantsIcon,
  SchoolIcon,
  ShipinglinesIcon,
  TradingIcon,
  TransportationIcon,
  TravelIcon,
} from "@/constant/icons";
export const serviceDataNew = [
  {
    title: "Retail & \nE-commerce",
    bg: "bg-thistle",
    border: "border-rosybrown",
    icon: <CartIcon />,
  },
  {
    title: "Fast Moving \nConsumer Goods",
    bg: "bg-lightyellow",
    border: "border-darkgray",
    icon: <FastMoveGoodsIcon />,
  },
  {
    title: "BFSI",
    bg: "bg-pink",
    border: "border-rosybrown_700",
    icon: <BfsiIcon />,
  },
  {
    title: "Edtech",
    bg: "bg-lavender",
    border: "border-lightsteelblue",
    icon: <EdtechIcon />,
  },
  {
    title: "Manufacturing",
    bg: "bg-pink_700",
    border: "border-rosybrown",
    icon: <ManufacturingIcon />,
  },
  {
    title: "Healthcare & Hospitals",
    bg: "bg-linen",
    border: "border-darkgray",
    icon: <HealthcareIcon />,
  },
  {
    title: "Marketing & Sales",
    bg: "bg-mistyrose",
    border: "border-rosybrown_700",
    icon: <MarketingIcon />,
  },
  {
    title: "Travel",
    bg: "bg-powderblue",
    border: "border-cadetblue",
    icon: <TravelIcon />,
  },
  {
    title: "School & \nUniversity",
    bg: "bg-lavender",
    border: "border-lightsteelblue",
    icon: <SchoolIcon />,
  },
  {
    title: "Trading Company",
    bg: "bg-thistle",
    border: "border-rosybrown",
    icon: <TradingIcon />,
  },
  {
    title: "Entertainment/OTT Platforms",
    bg: "bg-lightyellow",
    border: "border-darkgray",
    icon: <OttIcon />,
  },
  {
    title: "Government \nEntities",
    bg: "bg-pink",
    border: "border-rosybrown_700",
    icon: <GoventitiesIcon />,
  },
  {
    title: "Restaurants & \nHotels",
    bg: "bg-lavender",
    border: "border-lightsteelblue",
    icon: <RestaurantsIcon />,
  },
  {
    title: "Transportation & \nWarehouse",
    bg: "bg-pink_700",
    border: "border-rosybrown",
    icon: <TransportationIcon />,
  },
  {
    title: "Real Estate",
    bg: "bg-linen",
    border: "border-darkgray",
    icon: <RealestateIcon />,
  },
  {
    title: "Shipping Lines/\nCHA/CFS",
    bg: "bg-mistyrose",
    border: "border-rosybrown_700",
    icon: <ShipinglinesIcon />,
  },
];
